var search={
  "-": "http://hadrianswall.squirrel.link/data/road/8",
  "Beckfoot": "http://hadrianswall.squirrel.link/data/fort/19",
  "Benwell": "http://hadrianswall.squirrel.link/data/fort/4",
  "Bewcastle": "http://hadrianswall.squirrel.link/data/fort/33",
  "Binchester": "http://hadrianswall.squirrel.link/data/fort/38",
  "Birdoswald": "http://hadrianswall.squirrel.link/data/fort/12",
  "Birrens": "http://hadrianswall.squirrel.link/data/fort/36",
  "Bowness-on-Solway": "http://hadrianswall.squirrel.link/data/fort/18",
  "Brampton Old Church": "http://hadrianswall.squirrel.link/data/fort/14",
  "Brougham": "http://hadrianswall.squirrel.link/data/fort/39",
  "Burgh-by-Sands": "http://hadrianswall.squirrel.link/data/fort/16",
  "Burrow Walls": "http://hadrianswall.squirrel.link/data/fort/20",
  "Carlisle": "http://hadrianswall.squirrel.link/data/fort/23",
  "Carrawburgh": "http://hadrianswall.squirrel.link/data/fort/7",
  "Carvoran": "http://hadrianswall.squirrel.link/data/fort/11",
  "Castlesteads": "http://hadrianswall.squirrel.link/data/fort/13",
  "Chester-le-Street": "http://hadrianswall.squirrel.link/data/fort/27",
  "Chesters": "http://hadrianswall.squirrel.link/data/fort/8",
  "CoastalSite Instances Collection": "http://hadrianswall.squirrel.link/data/CoastalSite_collection",
  "Corbridge": "http://hadrianswall.squirrel.link/data/fort/25",
  "Cumbrian_Coast Instances Collection": "http://hadrianswall.squirrel.link/data/Cumbrian_Coast_collection",
  "Curtain_wall Instances Collection": "http://hadrianswall.squirrel.link/data/Curtain_wall_collection",
  "Dere Street": "http://hadrianswall.squirrel.link/data/road/22",
  "Drumburgh": "http://hadrianswall.squirrel.link/data/fort/17",
  "Ebchester": "http://hadrianswall.squirrel.link/data/fort/26",
  "Fort Instances Collection": "http://hadrianswall.squirrel.link/data/Fort_collection",
  "Great Chesters": "http://hadrianswall.squirrel.link/data/fort/10",
  "Hadrian%27s_Wall Instances Collection": "http://hadrianswall.squirrel.link/data/Hadrian%27s_Wall_collection",
  "HadriansWall Instances Collection": "http://hadrianswall.squirrel.link/data/HadriansWall_collection",
  "Halton Chesters": "http://hadrianswall.squirrel.link/data/fort/6",
  "High Rochester": "http://hadrianswall.squirrel.link/data/fort/35",
  "High Street": "http://hadrianswall.squirrel.link/data/road/19",
  "Housesteads": "http://hadrianswall.squirrel.link/data/fort/9",
  "Kirkby Thore": "http://hadrianswall.squirrel.link/data/fort/40",
  "Lanchester": "http://hadrianswall.squirrel.link/data/fort/28",
  "Maiden Way": "http://hadrianswall.squirrel.link/data/road/17",
  "Major_Road Instances Collection": "http://hadrianswall.squirrel.link/data/Major_Road_collection",
  "Maryport": "http://hadrianswall.squirrel.link/data/fort/21",
  "Milefortlet 1 (Biglands House)": "http://hadrianswall.squirrel.link/data/site/1",
  "Milefortlet 12 (Blitterlees)": "http://hadrianswall.squirrel.link/data/site/11",
  "Milefortlet 15a (Bank Hill)": "http://hadrianswall.squirrel.link/data/site/18",
  "Milefortlet 16 (Mawbray)": "http://hadrianswall.squirrel.link/data/site/27",
  "Milefortlet 17 (Dubmill Point)": "http://hadrianswall.squirrel.link/data/site/17",
  "Milefortlet 20 (Low Mire)": "http://hadrianswall.squirrel.link/data/site/19",
  "Milefortlet 21 (Swarthy Hill)": "http://hadrianswall.squirrel.link/data/site/21",
  "Milefortlet 22 (Brownrigg)": "http://hadrianswall.squirrel.link/data/site/23",
  "Milefortlet 23 (Sea Brows)": "http://hadrianswall.squirrel.link/data/site/24",
  "Milefortlet 3 (Pasture House)": "http://hadrianswall.squirrel.link/data/site/3",
  "Milefortlet 4 (Herd Hill)": "http://hadrianswall.squirrel.link/data/site/6",
  "Milefortlet 5 (Cardurnock)": "http://hadrianswall.squirrel.link/data/site/9",
  "Milefortlet 9 (Skinburness)": "http://hadrianswall.squirrel.link/data/site/10",
  "Milefortlet Instances Collection": "http://hadrianswall.squirrel.link/data/Milefortlet_collection",
  "Minor_Road Instances Collection": "http://hadrianswall.squirrel.link/data/Minor_Road_collection",
  "Moresby": "http://hadrianswall.squirrel.link/data/fort/22",
  "Netherby": "http://hadrianswall.squirrel.link/data/fort/34",
  "Newcastle": "http://hadrianswall.squirrel.link/data/fort/3",
  "Old Carlisle": "http://hadrianswall.squirrel.link/data/fort/29",
  "Old Penrith": "http://hadrianswall.squirrel.link/data/fort/31",
  "Outpost_Fort Instances Collection": "http://hadrianswall.squirrel.link/data/Outpost_Fort_collection",
  "Papcastle": "http://hadrianswall.squirrel.link/data/fort/30",
  "Risingham": "http://hadrianswall.squirrel.link/data/fort/32",
  "RomanRoad Instances Collection": "http://hadrianswall.squirrel.link/data/RomanRoad_collection",
  "Rudchester": "http://hadrianswall.squirrel.link/data/fort/5",
  "South Shields": "http://hadrianswall.squirrel.link/data/fort/1",
  "Stanegate": "http://hadrianswall.squirrel.link/data/road/18",
  "Stanegate Instances Collection": "http://hadrianswall.squirrel.link/data/Stanegate_collection",
  "Stanwix": "http://hadrianswall.squirrel.link/data/fort/15",
  "Support_Fort Instances Collection": "http://hadrianswall.squirrel.link/data/Support_Fort_collection",
  "The Devil's Causeway": "http://hadrianswall.squirrel.link/data/road/11",
  "Tower 12a (Blitterlees West)": "http://hadrianswall.squirrel.link/data/site/12",
  "Tower 12b (Blitterlees South)": "http://hadrianswall.squirrel.link/data/site/13",
  "Tower 13a (Wolsty North)": "http://hadrianswall.squirrel.link/data/site/14",
  "Tower 13b (Wolsty South)": "http://hadrianswall.squirrel.link/data/site/15",
  "Tower 16A (Cote Howe)": "http://hadrianswall.squirrel.link/data/site/26",
  "Tower 16b (Mawbray Sandpit)": "http://hadrianswall.squirrel.link/data/site/16",
  "Tower 20b (Swarthy Hill North)": "http://hadrianswall.squirrel.link/data/site/20",
  "Tower 21b (Brownrigg North)": "http://hadrianswall.squirrel.link/data/site/22",
  "Tower 25a (Risehow)": "http://hadrianswall.squirrel.link/data/site/25",
  "Tower 25b (Fothergill)": "http://hadrianswall.squirrel.link/data/site/28",
  "Tower 2b (Campfield)": "http://hadrianswall.squirrel.link/data/site/2",
  "Tower 3a (Pasture House West)": "http://hadrianswall.squirrel.link/data/site/4",
  "Tower 3b (Herd Hill North)": "http://hadrianswall.squirrel.link/data/site/5",
  "Tower 4a (Pow Drain)": "http://hadrianswall.squirrel.link/data/site/7",
  "Tower 4b (Cardurnock)": "http://hadrianswall.squirrel.link/data/site/8",
  "Tower Instances Collection": "http://hadrianswall.squirrel.link/data/Tower_collection",
  "Vallum Instances Collection": "http://hadrianswall.squirrel.link/data/Vallum_collection",
  "Vindolanda": "http://hadrianswall.squirrel.link/data/fort/24",
  "Wall_ditch Instances Collection": "http://hadrianswall.squirrel.link/data/Wall_ditch_collection",
  "Wallsend": "http://hadrianswall.squirrel.link/data/fort/2",
  "Whitley Castle": "http://hadrianswall.squirrel.link/data/fort/37",
  "Wrekendyke": "http://hadrianswall.squirrel.link/data/road/7",
  "the_geom Instances Collection": "http://hadrianswall.squirrel.link/data/the_geom_collection"
}