
name: CI


on:

  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

  workflow_dispatch: 


jobs:
 
  build:

    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with: 
        version: v017dev
        rdffilepath: ttl/coastal_sites_hw_result.ttl ttl/forts_hw_result.ttl ttl/hadrians_wall_result.ttl ttl/roman_roads_hw_result.ttl
        docpath: docs
        prefixns: http://hadrianswall.squirrel.link/data/
        prefixnsshort: haw
        indexpages: true
        createcollections: true
        createnonNSPages: true
        createVOWL: true
        metadatatable: true
        preferredlang: en
        license: CC BY-SA 4.0
        ghpages: true